apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-sidecar
  labels:
    app: nginx-sidecar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sidecar
  template:
    metadata:
      labels:
        app: nginx-sidecar
    spec:
      # Volumen compartido entre contenedores
      volumes:
      - name: shared-logs
        emptyDir: {}
      
      containers:
      # Contenedor principal: nginx
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      
      # Contenedor sidecar: procesador de logs
      - name: log-sidecar
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo '[SIDECAR] Procesando logs...'; tail -n 5 /logs/access.log 2>/dev/null || echo 'Esperando logs...'; sleep 10; done"]
        volumeMounts:
        - name: shared-logs
          mountPath: /logs
---
apiVersion: v1
kind: Service
metadata:
  name: web-service-sidecar
  labels:
    app: nginx-sidecar
spec:
  type: NodePort
  selector:
    app: nginx-sidecar
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
