apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv-manual
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/web
