# app-v1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        version: v1.0  # Etiqueta para identificar versión
    spec:
      containers:
      - name: webapp
        image: hashicorp/http-echo:0.2.3
        args:
          - "-text=Version 1.0"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 5678
  type: LoadBalancer