apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-volume
  labels:
    app: nginx-volume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-volume
  template:
    metadata:
      labels:
        app: nginx-volume
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-storage
        persistentVolumeClaim:
          claimName: web-pvc-manual
---
apiVersion: v1
kind: Service
metadata:
  name: web-service-volume
  labels:
    app: nginx-volume
spec:
  type: NodePort
  selector:
    app: nginx-volume
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30082